name: Vercel Production Deployment

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

on:
  push:
    branches:
      - main  # Trigger workflow on pushes to the main branch

jobs:
  Deploy-Production:
    name: Deploy to Vercel Production
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout Repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Install Vercel CLI
      - name: Install Vercel CLI
        run: npm install --global vercel

      # Step 3: Build and Deploy to Vercel
      - name: Deploy to Vercel
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        run: |
          vercel deploy \
            --prebuilt \
            --prod \
            --org-id $VERCEL_ORG_ID \
            --project-id $VERCEL_PROJECT_ID \
            --token $VERCEL_TOKEN
